spring.output.ansi.enabled: ALWAYS

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        format_sql: true

---
spring:
  data:
    mongodb:
      database: test
      uri: mongodb://admin:admin@localhost:27017,localhost:27018,localhost:27019/?replicaSet=replica-set&authSource=admin