spring.output.ansi.enabled: ALWAYS

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
---
spring:
  data:
    mongodb:
      database: test
      uri: mongodb://admin:admin@localhost:27017,localhost:27018,localhost:27019/?replicaSet=replica-set&authSource=admin&readPreference=secondaryPreferred&heartbeatFrequencyMS=300000